I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 203, in script call
    call _load_reload_game from _call__load_reload_game_1
  File "renpy/common/00keymap.rpy", line 450, in script
    python hide:
  File "renpy/common/00start.rpy", line 203, in script call
    call _load_reload_game from _call__load_reload_game_1
  File "renpy/common/00keymap.rpy", line 450, in script
    python hide:
  File "renpy/common/00keymap.rpy", line 450, in <module>
    python hide:
  File "renpy/common/00keymap.rpy", line 460, in _execute_python_hide
    renpy.load("_reload-2")
Exception: Couldn't find a place to stop rolling back. Perhaps the script changed in an incompatible way?

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "L:\Programs\Renpy\renpy-7.2.2-sdk\renpy\bootstrap.py", line 313, in bootstrap
    renpy.main.main()
  File "L:\Programs\Renpy\renpy-7.2.2-sdk\renpy\main.py", line 525, in main
    run(restart)
  File "L:\Programs\Renpy\renpy-7.2.2-sdk\renpy\main.py", line 139, in run
    renpy.execution.run_context(True)
  File "L:\Programs\Renpy\renpy-7.2.2-sdk\renpy\execution.py", line 892, in run_context
    context.run()
  File "renpy/common/00start.rpy", line 203, in script call
    call _load_reload_game from _call__load_reload_game_1
  File "renpy/common/00keymap.rpy", line 450, in script
    python hide:
  File "renpy/common/00start.rpy", line 203, in script call
    call _load_reload_game from _call__load_reload_game_1
  File "renpy/common/00keymap.rpy", line 450, in script
    python hide:
  File "L:\Programs\Renpy\renpy-7.2.2-sdk\renpy\ast.py", line 900, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "L:\Programs\Renpy\renpy-7.2.2-sdk\renpy\python.py", line 1930, in py_exec_bytecode
    exec bytecode in globals, locals
  File "renpy/common/00keymap.rpy", line 450, in <module>
    python hide:
  File "renpy/common/00keymap.rpy", line 460, in _execute_python_hide
    renpy.load("_reload-2")
  File "L:\Programs\Renpy\renpy-7.2.2-sdk\renpy\loadsave.py", line 753, in load
    log.unfreeze(roots, label="_after_load")
  File "L:\Programs\Renpy\renpy-7.2.2-sdk\renpy\python.py", line 1885, in unfreeze
    self.rollback(0, force=True, label=label, greedy=greedy, on_load=True)
  File "L:\Programs\Renpy\renpy-7.2.2-sdk\renpy\python.py", line 1713, in rollback
    raise Exception("Couldn't find a place to stop rolling back. Perhaps the script changed in an incompatible way?")
Exception: Couldn't find a place to stop rolling back. Perhaps the script changed in an incompatible way?

Windows-8-6.2.9200
Ren'Py 7.2.2.491
Hurricane Like Me 0.2
Fri Jun 21 23:26:45 2019
